name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Apply labels
        uses: actions/labeler@v5
        with:
          repo-token: "${{ github.token }}"
